# This is a basic workflow to help you get started with Actions



name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@master
   
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.DDKBOT_AZURE_CREDENTIALS }}

# Runs a single command using the runners shell

    - name: Setup Dotnet 4.7.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.7.7'

      

    - name: 'Run dotnet build'
      shell: bash
      run: |
        # If your web app project is not located in your repository's root
        # Please consider using pushd to change your path
        pushd .
        dotnet build --configuration Release --output ./output
        popd
        
        # deploy web app using Azure credentials
        - uses: azure/webapps-deploy@v2
          with:
          app-name: 'ddkbot-webapp-1'

        # Azure logout 
        - name: logout
          run: |
            az logout
